spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/devlog
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  security:
    basic:
      enabled: true

jwt:
  secret:
    key: 0I1dMgWg8tUJ64gIxs1JFVpKLF0bTQpezY76YKoSAxVzxpH98qjbEyLaWOSikfWEWT2o3eNx1Xsqv8oMCJq9HYJQwNzJ0zOBeetl